name: 📋🚨🔍📊 Retrieve GHAS Alerts 

on:
  workflow_dispatch:  

jobs:
  get_alerts:
    name: Get Alerts from APIs
    runs-on: ubuntu-latest
    steps:

    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    
    - name: Get Dependabot alerts using GitHub CLI      
      run: |
        gh api /repos/${{ github.repository }}/dependabot/alerts > dependabot-alerts.json
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

    - name: Upload Dependabot alerts as an artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: dependabot-alerts
        path: dependabot-alerts.json


    - name: Get CodeQL alerts using GitHub CLI
      run: |
        gh api /repos/${{ github.repository }}/code-scanning/alerts
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

    - name: Get Secret Scanning alerts using GitHub CLI
      run: |
        gh api /repos/${{ github.repository }}/secret-scanning/alerts
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}


    - name: Get Security alerts using GraphQL API
      run: |
        query='
          query () {  
            repository(owner: "0GiS0", name: "ghas-alerts-from-api") {
              nameWithOwner
              url
              vulnerabilityAlerts(first: 20) {
                nodes {
                  id
                  number
                  createdAt
                  state
                  vulnerableManifestPath
                  vulnerableRequirements        
                  securityVulnerability {
                    package {
                      name
                    }
                    advisory {
                      severity
                      summary
                      description
                      references {
                        url
                      }
                      identifiers {
                        type
                        value
                      }
                      cvss {
                        score     
                        vectorString        
                      }
                      cwes(first: 5) {              
                        nodes {
                          cweId
                          name
                          description
                        }
                      }
                    }
                  }        
                }
              }
              nameWithOwner
              url
            }
          }'
          
        gh api graphql -F query="${query}"
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}